# Generated by Django 5.0.2 on 2024-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='購買數量')),
                ('commodityinfos_id', models.IntegerField(verbose_name='商品Id')),
                ('user_id', models.IntegerField(verbose_name='用戶id')),
            ],
            options={
                'verbose_name': '購物車',
                'verbose_name_plural': '購物車',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(verbose_name='訂單總價')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('user_id', models.IntegerField(verbose_name='用戶id')),
                ('state', models.CharField(choices=[('待支付', '待支付'), ('已支付', '已支付'), ('發貨中', '發貨中'), ('已簽收', '已簽收'), ('退貨中', '退貨中')], max_length=20, verbose_name='訂單狀態')),
            ],
            options={
                'verbose_name': '訂單信息',
                'verbose_name_plural': '訂單信息',
            },
        ),
    ]
