# Generated by Django 5.0.2 on 2024-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='商品名稱')),
                ('size', models.CharField(max_length=100, verbose_name='顏色規格')),
                ('type', models.CharField(max_length=100, verbose_name='商品類型')),
                ('price', models.FloatField(verbose_name='商品價格')),
                ('discount', models.FloatField(verbose_name='折價後價格')),
                ('stock', models.IntegerField(verbose_name='存貨數量')),
                ('sold', models.IntegerField(verbose_name='已售數量')),
                ('likes', models.IntegerField(verbose_name='收藏數量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='上架日期')),
                ('img', models.FileField(upload_to='img', verbose_name='商品目錄')),
                ('details', models.FileField(upload_to='details', verbose_name='商品介紹')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=100, verbose_name='一級類型')),
                ('second', models.CharField(max_length=100, verbose_name='二級類型')),
            ],
            options={
                'verbose_name': '商品類型',
                'verbose_name_plural': '商品類型',
            },
        ),
    ]
